name: rb-mt4

task_name: rb-mt4
lazy_eval: true

shape_meta: &shape_meta
  obs:
    front_rgb:
      shape: [128, 128, 3]
      type: rgb
    wrist_rgb:
      shape: [128, 128, 3]
      type: rgb
    overhead_rgb:
      shape: [128, 128, 3]
      type: rgb
    joint_positions:
      shape: [7]
      type: state
    # gripper_pose:
    #   shape: [7]
    #   type: state
    gripper_joint_positions:
      shape: [2]
      type: state
  action:
    shape: [9]  # 7 dof + 2 gripper


env_runner:
  _target_: policy_research.env_runner.rlbench_runner.RlbenchRunner
  task_name: mt4
  n_test: 200
  n_test_vis: 8
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  n_parallel_envs: 40
  image_size: 128
  camera_names: ['front', 'wrist', 'overhead']
  state_ports:
    - joint_positions
    # - gripper_pose
    - gripper_joint_positions
  max_episode_steps: 250


dataset:
  _target_: policy_research.dataset.zarr_dataset.ZarrDataset
  zarr_path: data/rlbench/mt4_N${training.num_demo}.zarr
  obs_keys:
    - front_rgb
    - wrist_rgb
    - overhead_rgb
    - joint_positions
    # - gripper_pose
    - gripper_joint_positions
  action_key: delta_joint_action
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${horizon}
  seed: ${seed}
  val_ratio: 0.1
  